export {
  xeyyConfigSchema,
  componentsConfigSchema,
  themeConfigSchema,
  aliasesConfigSchema,
  registriesConfigSchema,
  registryConfigSchema,
  iconLibraryConfigSchema,
  type XeyyConfig,
  type ComponentsConfig,
  type ThemeConfig,
  type AliasesConfig,
  type RegistriesConfig,
  type RegistryConfig,
} from './schema.ts';

export {
  defaultConfig,
  DEFAULT_ICON_LIBRARY,
  getConfigPath,
  configExists,
  loadConfig,
  readConfig,
  writeConfig,
  createDefaultConfig,
  ensureDir,
  resolveComponentPath,
  resolveThemePath,
  resolveRegistryDir,
  resolveRegistrySource,
  resolveRegistryDist,
  resolveRegistryThemeSource,
  resolveRegistryAlias,
  getRegistryUrl,
  resolveIconLibrary,
  type ConfigValidationResult,
  type ConfigValidationIssue,
} from './config.ts';