/**
 * STYLE_RECIPES — the single source of truth for every Style.
 *
 * Hand-transcribed from upstream style-<name>.css `@apply` lines (via the
 * audit extract) using the mapping rules documented in recipe.ts. Values are
 * plain CSS literals (Tailwind v4 spacing/radius resolved to rem) so the
 * module stays free of `@stylexjs/stylex` and can be imported by plain Node
 * tooling and by consumer runtimes.
 *
 * Shadows reuse the fixed Tailwind v4 shadow literals; styles only differ in
 * which step they apply. There is no separate dark shadow set upstream.
 */
import type { RadiusStep } from './scale.ts';
import type { StyleName, StyleRecipes } from './recipe.ts';

const SHADOW_XS = '0 1px 2px 0 rgb(0 0 0 / 0.05)';
const SHADOW_SM = '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)';
const SHADOW_MD = '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)';
const SHADOW_LG = '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)';
const SHADOW_XL = '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)';
const SHADOW_2XL = '0 25px 50px -12px rgb(0 0 0 / 0.25)';

const md: RadiusStep = 'md';
const lg: RadiusStep = 'lg';
const xl: RadiusStep = 'xl';
const none: RadiusStep = 'none';
const sm: RadiusStep = 'sm';
const full: RadiusStep = 'full';
const twoXl: RadiusStep = '2xl';
const threeXl: RadiusStep = '3xl';
const fourXl: RadiusStep = '4xl';

export const STYLE_RECIPES: Record<StyleName, StyleRecipes> = {
  vega: {
    button: {
      radius: md,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '2rem',
      gap: '0.25rem',
      radius: md,
      paddingInline: '0.625rem',
    },
    buttonSizeDefault: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeLg: {
      height: '2.5rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeIcon: {
      height: '2.25rem',
      width: '2.25rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: fourXl,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1.5rem',
      gap: '1.5rem',
      radius: xl,
      fontSize: '0.875rem',
      boxShadow: SHADOW_XS,
    },
    cardHeader: {
      gap: '0.25rem',
      paddingInline: '1.5rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1.5rem',
      radius: xl,
      padding: '1.5rem',
      fontSize: '0.875rem',
    },
    menuContent: {
      minWidth: '8rem',
      padding: '0.25rem',
      radius: md,
      boxShadow: SHADOW_MD,
    },
    menuItem: {
      gap: '0.5rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.375rem',
      radius: sm,
      fontSize: '0.875rem',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: md,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '1rem',
      radius: md,
      fontSize: '0.875rem',
      boxShadow: SHADOW_MD,
    },
    input: {
      height: '2.25rem',
      paddingInline: '0.625rem',
      paddingBlock: '0.25rem',
      radius: md,
      fontSize: '1rem',
      boxShadow: SHADOW_XS,
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.625rem',
      paddingBlock: '0.5rem',
      radius: md,
      fontSize: '1rem',
      boxShadow: SHADOW_XS,
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2.25rem',
      paddingBlock: '0.5rem',
      paddingRight: '0.5rem',
      paddingLeft: '0.625rem',
      radius: md,
      fontSize: '0.875rem',
      boxShadow: SHADOW_XS,
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '3px',
      radius: lg,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.25rem',
      radius: md,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      paddingBlock: '1rem',
      radius: md,
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: md,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '4px',
      boxShadow: SHADOW_XS,
      borderWidth: '1px',
    },
    switch: {
      height: '18.4px',
      width: '32px',
      radius: full,
      boxShadow: SHADOW_XS,
      borderWidth: '1px',
    },
    progress: {
      height: '0.375rem',
      radius: full,
    },
    skeleton: {
      radius: md,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      padding: '0.5rem',
      radius: md,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.375rem',
      radius: full,
    },
  },

  nova: {
    button: {
      radius: lg,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '1.75rem',
      gap: '0.25rem',
      paddingInline: '0.625rem',
      radius: md,
      fontSize: '0.8rem',
      iconSize: '0.875rem',
    },
    buttonSizeDefault: {
      height: '2rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeLg: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeIcon: {
      height: '2rem',
      width: '2rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: fourXl,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1rem',
      gap: '1rem',
      radius: xl,
      fontSize: '0.875rem',
    },
    cardHeader: {
      gap: '0.25rem',
      paddingInline: '1rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1rem',
      radius: xl,
      padding: '1rem',
      fontSize: '0.875rem',
    },
    menuContent: {
      minWidth: '8rem',
      padding: '0.25rem',
      radius: lg,
      boxShadow: SHADOW_MD,
    },
    menuItem: {
      gap: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.25rem',
      radius: md,
      fontSize: '0.875rem',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: md,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '0.625rem',
      padding: '0.625rem',
      radius: lg,
      fontSize: '0.875rem',
      boxShadow: SHADOW_MD,
    },
    input: {
      height: '2rem',
      paddingInline: '0.625rem',
      paddingBlock: '0.25rem',
      radius: lg,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.625rem',
      paddingBlock: '0.5rem',
      radius: lg,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2rem',
      paddingBlock: '0.5rem',
      paddingRight: '0.5rem',
      paddingLeft: '0.625rem',
      radius: lg,
      fontSize: '0.875rem',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '3px',
      radius: lg,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.125rem',
      radius: md,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      paddingBlock: '0.625rem',
      radius: lg,
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: lg,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '4px',
      borderWidth: '1px',
    },
    switch: {
      height: '18.4px',
      width: '32px',
      radius: full,
      borderWidth: '1px',
    },
    progress: {
      height: '0.25rem',
      radius: full,
    },
    skeleton: {
      radius: md,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      padding: '0.5rem',
      radius: md,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.25rem',
      radius: full,
    },
  },

  maia: {
    button: {
      radius: fourXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '2rem',
      gap: '0.25rem',
      paddingInline: '0.75rem',
    },
    buttonSizeDefault: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '0.75rem',
    },
    buttonSizeLg: {
      height: '2.5rem',
      gap: '0.375rem',
      paddingInline: '1rem',
    },
    buttonSizeIcon: {
      height: '2.25rem',
      width: '2.25rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: fourXl,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1.5rem',
      gap: '1.5rem',
      radius: twoXl,
      fontSize: '0.875rem',
    },
    cardHeader: {
      gap: '0.5rem',
      paddingInline: '1.5rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1.5rem',
      radius: fourXl,
      padding: '1.5rem',
      fontSize: '0.875rem',
    },
    menuContent: {
      minWidth: '12rem',
      padding: '0.25rem',
      radius: twoXl,
      boxShadow: SHADOW_2XL,
    },
    menuItem: {
      gap: '0.625rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: xl,
      fontSize: '0.875rem',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: twoXl,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '1rem',
      radius: twoXl,
      fontSize: '0.875rem',
      boxShadow: SHADOW_2XL,
    },
    input: {
      height: '2.25rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.25rem',
      radius: fourXl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.75rem',
      paddingBlock: '0.75rem',
      radius: xl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2.25rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: fourXl,
      fontSize: '0.875rem',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '3px',
      radius: fourXl,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.25rem',
      radius: xl,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      gap: '1.5rem',
      padding: '1rem',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: fourXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '6px',
      borderWidth: '1px',
    },
    switch: {
      height: '18.4px',
      width: '32px',
      radius: full,
      borderWidth: '1px',
    },
    progress: {
      height: '0.75rem',
      radius: fourXl,
    },
    skeleton: {
      radius: xl,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: lg,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.75rem',
      radius: fourXl,
    },
  },

  lyra: {
    button: {
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '1.75rem',
      gap: '0.25rem',
      paddingInline: '0.625rem',
      radius: none,
      iconSize: '0.875rem',
    },
    buttonSizeDefault: {
      height: '2rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeLg: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '0.625rem',
    },
    buttonSizeIcon: {
      height: '2rem',
      width: '2rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1rem',
      gap: '1rem',
      radius: none,
      fontSize: '0.75rem',
      lineHeight: '1.625',
    },
    cardHeader: {
      gap: '0.25rem',
      paddingInline: '1rem',
      radius: none,
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1rem',
      radius: none,
      padding: '1rem',
      fontSize: '0.75rem',
      lineHeight: '1.625',
    },
    menuContent: {
      minWidth: '8rem',
      radius: none,
      boxShadow: SHADOW_MD,
    },
    menuItem: {
      gap: '0.5rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.5rem',
      radius: none,
      fontSize: '0.75rem',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: none,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '0.625rem',
      padding: '0.625rem',
      radius: none,
      fontSize: '0.75rem',
      boxShadow: SHADOW_MD,
    },
    input: {
      height: '2rem',
      paddingInline: '0.625rem',
      paddingBlock: '0.25rem',
      radius: none,
      fontSize: '0.75rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.625rem',
      paddingBlock: '0.5rem',
      radius: none,
      fontSize: '0.75rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2rem',
      paddingBlock: '0.5rem',
      paddingRight: '0.5rem',
      paddingLeft: '0.625rem',
      radius: none,
      fontSize: '0.75rem',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '3px',
      radius: none,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.125rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      paddingBlock: '0.625rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      radius: none,
      borderWidth: '1px',
    },
    switch: {
      height: '18.4px',
      width: '32px',
      radius: full,
      borderWidth: '1px',
    },
    progress: {
      height: '0.25rem',
      radius: none,
    },
    skeleton: {
      radius: none,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      padding: '0.5rem',
      radius: none,
      fontSize: '0.75rem',
    },
    sliderTrack: {
      height: '0.25rem',
      radius: none,
    },
  },

  mira: {
    button: {
      radius: md,
      fontSize: '0.75rem',
      lineHeight: '1.625',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '1.5rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      radius: sm,
      fontSize: '0.75rem',
      lineHeight: '1.625',
      iconSize: '0.75rem',
    },
    buttonSizeDefault: {
      height: '1.75rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      fontSize: '0.75rem',
      lineHeight: '1.625',
      iconSize: '0.875rem',
    },
    buttonSizeLg: {
      height: '2rem',
      gap: '0.25rem',
      paddingInline: '0.625rem',
      fontSize: '0.75rem',
      lineHeight: '1.625',
      iconSize: '1rem',
    },
    buttonSizeIcon: {
      height: '1.75rem',
      width: '1.75rem',
      iconSize: '0.875rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: full,
      fontSize: '0.625rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1rem',
      gap: '1rem',
      radius: lg,
      fontSize: '0.75rem',
      lineHeight: '1.625',
    },
    cardHeader: {
      gap: '0.25rem',
      paddingInline: '1rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1rem',
      radius: xl,
      padding: '1rem',
      fontSize: '0.75rem',
      lineHeight: '1.625',
    },
    menuContent: {
      minWidth: '8rem',
      padding: '0.25rem',
      radius: lg,
      boxShadow: SHADOW_MD,
    },
    menuItem: {
      gap: '0.5rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.25rem',
      radius: md,
      fontSize: '0.75rem',
      lineHeight: '1.625',
      iconSize: '0.875rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: md,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '0.625rem',
      radius: lg,
      fontSize: '0.75rem',
      boxShadow: SHADOW_MD,
    },
    input: {
      height: '1.75rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: md,
      fontSize: '0.875rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.5rem',
      paddingBlock: '0.5rem',
      radius: md,
      fontSize: '0.875rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '1.75rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.375rem',
      radius: md,
      fontSize: '0.75rem',
      lineHeight: '1.625',
      borderWidth: '1px',
      iconSize: '0.875rem',
    },
    tabsList: {
      padding: '3px',
      radius: lg,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.125rem',
      radius: md,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '0.875rem',
    },
    accordionTrigger: {
      gap: '1.5rem',
      padding: '0.5rem',
      fontSize: '0.75rem',
      lineHeight: '1.625',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: md,
      fontSize: '0.75rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '4px',
      borderWidth: '1px',
    },
    switch: {
      height: '16.6px',
      width: '28px',
      radius: full,
      borderWidth: '1px',
    },
    progress: {
      height: '0.25rem',
      radius: md,
    },
    skeleton: {
      radius: md,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      padding: '0.5rem',
      radius: md,
      fontSize: '0.75rem',
    },
    sliderTrack: {
      height: '0.25rem',
      radius: md,
    },
  },

  luma: {
    button: {
      radius: fourXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '2rem',
      gap: '0.25rem',
      paddingInline: '0.75rem',
    },
    buttonSizeDefault: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '0.75rem',
    },
    buttonSizeLg: {
      height: '2.5rem',
      gap: '0.375rem',
      paddingInline: '1rem',
    },
    buttonSizeIcon: {
      height: '2.25rem',
      width: '2.25rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: threeXl,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1.5rem',
      gap: '1.5rem',
      radius: fourXl,
      fontSize: '0.875rem',
      boxShadow: SHADOW_MD,
    },
    cardHeader: {
      gap: '0.375rem',
      paddingInline: '1.5rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1.5rem',
      radius: fourXl,
      padding: '1.5rem',
      fontSize: '0.875rem',
      boxShadow: SHADOW_XL,
    },
    menuContent: {
      minWidth: '12rem',
      padding: '0.375rem',
      radius: threeXl,
      boxShadow: SHADOW_LG,
    },
    menuItem: {
      gap: '0.625rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: twoXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: xl,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '1rem',
      radius: threeXl,
      fontSize: '0.875rem',
      boxShadow: SHADOW_LG,
    },
    input: {
      height: '2.25rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.25rem',
      radius: threeXl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.75rem',
      paddingBlock: '0.75rem',
      radius: twoXl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2.25rem',
      paddingBlock: '0.5rem',
      paddingInline: '0.75rem',
      radius: threeXl,
      fontSize: '0.875rem',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '0.25rem',
      radius: full,
    },
    tabsTrigger: {
      gap: '0.5rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.25rem',
      radius: full,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      gap: '1.5rem',
      padding: '1rem',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: threeXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '5px',
      borderWidth: '1px',
    },
    switch: {
      height: '1.25rem',
      width: '2.75rem',
      radius: full,
      borderWidth: '2px',
    },
    progress: {
      height: '0.75rem',
      radius: full,
    },
    skeleton: {
      radius: twoXl,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: xl,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.5rem',
      radius: full,
    },
  },

  rhea: {
    button: {
      radius: twoXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    buttonSizeSm: {
      height: '1.75rem',
      gap: '0.25rem',
      paddingInline: '0.75rem',
    },
    buttonSizeDefault: {
      height: '2rem',
      gap: '0.375rem',
      paddingInline: '0.75rem',
    },
    buttonSizeLg: {
      height: '2.25rem',
      gap: '0.375rem',
      paddingInline: '1rem',
    },
    buttonSizeIcon: {
      height: '2rem',
      width: '2rem',
    },
    badge: {
      height: '1.25rem',
      gap: '0.25rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.125rem',
      radius: twoXl,
      fontSize: '0.75rem',
      fontWeight: '500',
      borderWidth: '1px',
    },
    card: {
      paddingBlock: '1.25rem',
      gap: '1.25rem',
      borderRadius: 'min(calc(0.625rem + 24px), 24px)',
      fontSize: '0.875rem',
      boxShadow: SHADOW_SM,
    },
    cardHeader: {
      gap: '0.375rem',
      paddingInline: '1.25rem',
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1.5rem',
      borderRadius: 'min(calc(0.625rem + 24px), 24px)',
      padding: '1.5rem',
      fontSize: '0.875rem',
      boxShadow: SHADOW_XL,
    },
    menuContent: {
      minWidth: '8rem',
      padding: '0.25rem',
      radius: twoXl,
      boxShadow: SHADOW_LG,
    },
    menuItem: {
      gap: '0.5rem',
      paddingInline: '0.5rem',
      paddingBlock: '0.375rem',
      radius: xl,
      fontSize: '0.875rem',
      iconSize: '1rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: xl,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '1rem',
      radius: threeXl,
      fontSize: '0.875rem',
      boxShadow: SHADOW_LG,
    },
    input: {
      height: '2rem',
      paddingInline: '0.625rem',
      paddingBlock: '0.25rem',
      radius: twoXl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    textarea: {
      paddingInline: '0.625rem',
      paddingBlock: '0.5rem',
      radius: twoXl,
      fontSize: '1rem',
      borderWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2rem',
      paddingBlock: '0.5rem',
      paddingInline: '0.75rem',
      radius: twoXl,
      fontSize: '0.875rem',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    tabsList: {
      padding: '3px',
      radius: twoXl,
    },
    tabsTrigger: {
      gap: '0.375rem',
      paddingInline: '0.375rem',
      paddingBlock: '0.125rem',
      radius: twoXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      borderWidth: '1px',
      iconSize: '1rem',
    },
    accordionTrigger: {
      gap: '1.5rem',
      padding: '1rem',
      fontSize: '0.875rem',
      fontWeight: '500',
    },
    toggle: {
      gap: '0.25rem',
      radius: twoXl,
      fontSize: '0.875rem',
      fontWeight: '500',
      iconSize: '1rem',
    },
    checkbox: {
      height: '1rem',
      width: '1rem',
      borderRadius: '5px',
      borderWidth: '1px',
    },
    switch: {
      height: '1.25rem',
      width: '2rem',
      radius: twoXl,
      borderWidth: '2px',
    },
    progress: {
      height: '0.5rem',
      radius: twoXl,
    },
    skeleton: {
      radius: twoXl,
    },
    sidebarMenuButton: {
      gap: '0.5rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: xl,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.25rem',
      radius: twoXl,
    },
  },

  sera: {
    button: {
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '600',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      borderWidth: '1px',
      iconSize: '0.875rem',
    },
    buttonSizeSm: {
      height: '2.25rem',
      gap: '0.25rem',
      paddingInline: '1rem',
    },
    buttonSizeDefault: {
      height: '2.5rem',
      gap: '0.375rem',
      paddingInline: '1.5rem',
    },
    buttonSizeLg: {
      height: '2.75rem',
      gap: '0.375rem',
      paddingInline: '2rem',
    },
    buttonSizeIcon: {
      height: '2.5rem',
      width: '2.5rem',
    },
    badge: {
      gap: '0.375rem',
      paddingInline: '0',
      paddingBlock: '0',
      radius: none,
      fontSize: '0.625rem',
      fontWeight: '600',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      borderWidth: '0',
    },
    card: {
      paddingBlock: '2rem',
      gap: '2rem',
      fontSize: '0.875rem',
      boxShadow: SHADOW_SM,
    },
    cardHeader: {
      gap: '0.375rem',
      paddingInline: '2rem',
      radius: none,
    },
    dialogContent: {
      maxWidth: 'calc(100% - 2rem)',
      gap: '1.5rem',
      radius: none,
      padding: '1.5rem',
      fontSize: '0.875rem',
      boxShadow: SHADOW_MD,
    },
    menuContent: {
      minWidth: '12rem',
      padding: '0.375rem',
      radius: none,
      boxShadow: SHADOW_MD,
    },
    menuItem: {
      gap: '0.625rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '500',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      iconSize: '0.875rem',
    },
    tooltipContent: {
      gap: '0.375rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.375rem',
      radius: none,
      fontSize: '0.75rem',
    },
    popoverContent: {
      gap: '1rem',
      padding: '1rem',
      radius: none,
      fontSize: '0.875rem',
      boxShadow: SHADOW_MD,
    },
    input: {
      height: '2.5rem',
      paddingInline: '0',
      paddingBlock: '0.25rem',
      fontSize: '1rem',
      borderWidth: '1px',
      borderBottomWidth: '1px',
    },
    textarea: {
      paddingInline: '0',
      paddingBlock: '0.75rem',
      radius: none,
      fontSize: '1rem',
      borderWidth: '1px',
      borderBottomWidth: '1px',
    },
    selectTrigger: {
      gap: '0.375rem',
      height: '2.5rem',
      paddingBlock: '0.5rem',
      paddingInline: '0',
      radius: none,
      fontSize: '0.875rem',
      borderWidth: '1px',
      borderBottomWidth: '1px',
      iconSize: '0.875rem',
    },
    tabsList: {
      padding: '0.25rem',
    },
    tabsTrigger: {
      gap: '0.5rem',
      paddingInline: '1rem',
      paddingBlock: '0.375rem',
      fontSize: '0.75rem',
      fontWeight: '600',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      borderWidth: '1px',
      iconSize: '0.875rem',
    },
    accordionTrigger: {
      gap: '1.5rem',
      paddingBlock: '1rem',
      radius: none,
      fontSize: '0.875rem',
      fontWeight: '600',
    },
    toggle: {
      gap: '0.375rem',
      radius: none,
      fontSize: '0.75rem',
      fontWeight: '600',
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      iconSize: '0.875rem',
    },
    checkbox: {
      height: '1.125rem',
      width: '1.125rem',
      radius: none,
      borderWidth: '1px',
    },
    switch: {
      height: '1.125rem',
      width: '2.0625rem',
      radius: none,
      borderWidth: '1px',
    },
    progress: {
      height: '0.125rem',
      radius: none,
    },
    skeleton: {},
    sidebarMenuButton: {
      gap: '0.5rem',
      paddingInline: '0.75rem',
      paddingBlock: '0.5rem',
      radius: none,
      fontSize: '0.875rem',
    },
    sliderTrack: {
      height: '0.125rem',
    },
  },
};