import {
  createDefaultConfig,
  ensureDir,
  getConfigPath,
  configExists,
  readConfig,
  writeConfig,
  loadConfig,
  resolveComponentPath,
  resolveThemePath,
  resolveRegistryDir,
  resolveRegistrySource,
  resolveRegistryDist,
  resolveRegistryThemeSource,
  resolveRegistryAlias,
  getRegistryUrl,
  type XeyyConfig,
  type ConfigValidationResult,
  type ConfigValidationIssue,
  type RegistryConfig,
} from '@xeyy/config';

export {
  createDefaultConfig,
  ensureDir,
  getConfigPath,
  configExists,
  readConfig,
  writeConfig,
  loadConfig,
  resolveComponentPath,
  resolveThemePath,
  resolveRegistryDir,
  resolveRegistrySource,
  resolveRegistryDist,
  resolveRegistryThemeSource,
  resolveRegistryAlias,
  getRegistryUrl,
  type XeyyConfig,
  type ConfigValidationResult,
  type ConfigValidationIssue,
  type RegistryConfig,
};